-- DATA

-- STAR_TABLE
INSERT INTO PRIDEPROT.STAR (STAR_ID, STAR_COUNT, STAR_TYPE)
  VALUES (1, 0.0, N'NONE');

INSERT INTO PRIDEPROT.STAR (STAR_ID, STAR_COUNT, STAR_TYPE)
  VALUES (2, 1.0, N'BRONZE');

INSERT INTO PRIDEPROT.STAR (STAR_ID, STAR_COUNT, STAR_TYPE)
  VALUES (3, 1.0, N'SILVER');

INSERT INTO PRIDEPROT.STAR (STAR_ID, STAR_COUNT, STAR_TYPE)
  VALUES (4, 1.0, N'GOLD');

INSERT INTO PRIDEPROT.STAR (STAR_ID, STAR_COUNT, STAR_TYPE)
  VALUES (5, 2.0, N'BRONZE');

INSERT INTO PRIDEPROT.STAR (STAR_ID, STAR_COUNT, STAR_TYPE)
  VALUES (6, 2.0, N'SILVER');

INSERT INTO PRIDEPROT.STAR (STAR_ID, STAR_COUNT, STAR_TYPE)
  VALUES (7, 2.0, N'GOLD');

INSERT INTO PRIDEPROT.STAR (STAR_ID, STAR_COUNT, STAR_TYPE)
  VALUES (8, 3.0, N'BRONZE');

INSERT INTO PRIDEPROT.STAR (STAR_ID, STAR_COUNT, STAR_TYPE)
  VALUES (9, 3.0, N'SILVER');

INSERT INTO PRIDEPROT.STAR (STAR_ID, STAR_COUNT, STAR_TYPE)
  VALUES (10, 3.0, N'GOLD');


-- Q_METHOD_TABLE
INSERT INTO PRIDEPROT.Q_METHOD (Q_METHOD_ID, NAME, DESCRIPTION)
  VALUES (1, N'default', N'Default value to initialize the database');


-- SCORE_TABLE
-- None
INSERT INTO PRIDEPROT.SCORE (SCORE_ID, Q_METHOD_ID, STAR_ID, VALUE)
  VALUES (1, 1.0, 1.0, 0.0);

-- None
INSERT INTO PRIDEPROT.SCORE (SCORE_ID, Q_METHOD_ID, STAR_ID, VALUE)
  VALUES (2, 1.0, 5.0, 3.0);

-- None
INSERT INTO PRIDEPROT.SCORE (SCORE_ID, Q_METHOD_ID, STAR_ID, VALUE)
  VALUES (3, 1.0, 1.0, 5.0);

-- Silver
INSERT INTO PRIDEPROT.SCORE (SCORE_ID, Q_METHOD_ID, STAR_ID, VALUE)
  VALUES (4, 1.0, 9.0, 3.0);

-- Gold
INSERT INTO PRIDEPROT.SCORE (SCORE_ID, Q_METHOD_ID, STAR_ID, VALUE)
  VALUES (5, 1.0, 10.0, 3.0);

-- Silver
INSERT INTO PRIDEPROT.SCORE (SCORE_ID, Q_METHOD_ID, STAR_ID, VALUE)
  VALUES (6, 1.0, 3.0, 1.0);

-- Gold
INSERT INTO PRIDEPROT.SCORE (SCORE_ID, Q_METHOD_ID, STAR_ID, VALUE)
  VALUES (7, 1.0, 7.0, 2.5);

-- Gold
INSERT INTO PRIDEPROT.SCORE (SCORE_ID, Q_METHOD_ID, STAR_ID, VALUE)
  VALUES (8, 1.0, 7.0, 1.0);


--Protein features supported
INSERT INTO PRIDEPROT.CV_PARAM (CV_TERM, CV_NAME, CV_TYPE, DESCRIPTION)
  VALUES ('FT:000001', 'SIGNAL', 'FEATURE_TYPE', 'signal peptide');

INSERT INTO PRIDEPROT.CV_PARAM (CV_TERM, CV_NAME, CV_TYPE, DESCRIPTION)
  VALUES ('FT:000002', 'TOPO_DOM', 'FEATURE_TYPE', 'topological domain');

INSERT INTO PRIDEPROT.CV_PARAM (CV_TERM, CV_NAME, CV_TYPE, DESCRIPTION)
  VALUES ('FT:000003', 'TRANSMEM', 'FEATURE_TYPE', 'transmembrane region');

INSERT INTO PRIDEPROT.CV_PARAM (CV_TERM, CV_NAME, CV_TYPE, DESCRIPTION)
  VALUES ('FT:000004', 'INTRAMEM', 'FEATURE_TYPE', 'intramembrane region');

INSERT INTO PRIDEPROT.CV_PARAM (CV_TERM, CV_NAME, CV_TYPE, DESCRIPTION)
  VALUES ('FT:000005', 'PROPEP', 'FEATURE_TYPE', 'propeptide');