TRUNCATE TABLE PRIDEPROT.PROT_CV  ;
TRUNCATE TABLE PRIDEPROT.PEP_CV  ;
TRUNCATE TABLE PRIDEPROT.ASSAY_CV  ;
TRUNCATE TABLE PRIDEPROT.PEP_ASSAY  ;
TRUNCATE TABLE PRIDEPROT.PEP_CLUSTER  ;
TRUNCATE TABLE PRIDEPROT.PEP_MOD  ;
TRUNCATE TABLE PRIDEPROT.PEP_PROT  ;
TRUNCATE TABLE PRIDEPROT.PROT_GROUP  ;
TRUNCATE TABLE PRIDEPROT.PROT_MOD  ;
TRUNCATE TABLE PRIDEPROT.PROT_PGRP  ;
TRUNCATE TABLE PRIDEPROT.CLUSTER_PSM  ;

--Delete doesn't need to disable the fk_constrains but it is slower than truncate (truncate can not be rollback)
DELETE PRIDEPROT.PROTEIN ;
DELETE PRIDEPROT.PEPTIDE  ;
DELETE PRIDEPROT.PRIDE_CLUSTER  ;
DELETE PRIDEPROT.ASSAY  ;
DELETE PRIDEPROT.CV_PARAM  ;
--DELETE PRIDEPROT.MOD ;
